/**
 *
 * $Id$
 */
package softwareSystem.validation;

import org.eclipse.emf.common.util.EList;

import softwareSystem.Component;
import softwareSystem.SIL;

/**
 * A sample validator interface for {@link softwareSystem.Component}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ComponentValidator {
	boolean validate();

	boolean validateImports(EList<Component> value);

	boolean validateName(String value);

	boolean validateFunctionPoints(int value);

	boolean validateSil(SIL value);
}
