/**
 *
 * $Id$
 */
package softwareSystem.validation;

import org.eclipse.emf.common.util.EList;

import softwareSystem.Component;

/**
 * A sample validator interface for {@link softwareSystem.System}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SystemValidator {
	boolean validate();

	boolean validateSubSystems(EList<softwareSystem.System> value);

	boolean validateComponents(EList<Component> value);

	boolean validateName(String value);
}
